package cl.utalca.gismb;

public enum AccionesServlet {
	
	OBTENER_PROYECTOS,
	OBTENER_CAPAS_VECTORIALES_PROYECTO,
	GUARDAR_PROYECTO,
	GUARDAR_FIGURA_GEOMETRICA,
	GUARDAR_CAPA_VECTORIAL,
	GUARDAR_ATRIBUTOS_NUMERICOS,
	GUARDAR_ATRIBUTOS_TEXTO,
	GUARDAR_ATRIBUTOS_LOGICOS,
	GUARDAR_POSICION_ACTUAL_CAMARA,
	ELIMINAR_PROYECTO,
	ELIMINAR_CAPA_VECTORIAL,
	ELIMINAR_FIGURA_GEOMETRICA,
	ELIMINAR_ATRIBUTOS_FIGURA_GEOMETRICA,
	MODIFICAR_PROYECTO,
	MODIFICAR_CAPA_VECTORIAL,
	MODIFICAR_FIGURA_GEOMETRICA,
	MODIFICAR_NOMBRE_ATRIBUTO,
	ACTUALIZAR_VISIBILIDAD_CAPA,
	ACTUALIZAR_VALORES_ATRIBUTOS,
	CALCULOS_ESTADISTICA_BASICA,
	OBTENER_NOMBRES_ATRIBUTOS_NUMERICOS,
	INTERPOLACION,
	IMAGEN_INTERPOLACION,
	MOSTRAR_IMAGEN,
	VERIFICAR_POLIGONO
	

}
